### ISSUE TITLE
Code reformatting

### ISSUE THREAD

**Issue by alixsep** [BaseMax/Image-Generator-C#1]
The way the source has been formatted is cursed. Please fix it before Jesus sends us both to hell.

_Expected formatting:_

<img src="https://github.com/user-attachments/assets/9fde7f4a-7e06-4e8d-8039-c9cafb5778a0" width="400px" />

**Comment by BaseMax** [comment]
The main thing was to do this interesting idea in a beautiful way that the source code of the code looks like a character in reality.

Let me know if you need any kind of help.

**Comment by alixsep** [comment]
> looks like a character in reality.

Chief, I don't know what reality you live in, cause it looks like floor -666 of the hell. tomorrow i go to church to pray father forgives your sins so you escape the eternal suffering (by the so-called merciful god)

Edit: I'm just a penguin there's no church in Antarctica. (yet)

**Comment by BaseMax** [comment]
Haha, I guess we've reached floor -666 in code formatting! Looks like I've accidentally opened the gates to coding purgatory! 😈 But honestly, just trying to have some fun with it. Let's make the code heavenly together. 😇 Happy coding!

**Comment by alixsep** [comment]
Well shit man, i always knew you're crazy talented, I'd love every second spent with you. <3

btw keep the formatting this way, if it wasn't this way we wouldn't know each other, as it wouldn't have caught my attention to open an issue on it.
